module.exports = {
  movies: [
    {
      title: "Harry Potter and the Philosopher's Stone",
      release_date: '2001-11-14',
      country_id: 2,
      studio_id: 19,
      // director_id: 1,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Star Wars: Episode I – The Phantom Menace',
      release_date: '1999-05-19',
      country_id: 1,
      studio_id: 1,
      // director_id: 2,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Avatar',
      release_date: '2009-12-17',
      country_id: 1,
      studio_id: 2,
      // director_id: 3,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Die Hard',
      release_date: '1988-07-22',
      country_id: 1,
      studio_id: 2,
      // director_id: 4,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Leon: The Professional',
      release_date: '1994-09-14',
      country_id: 4,
      studio_id: 18,
      // director_id: 5,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Fifth Element',
      release_date: '1997-05-07',
      country_id: 4,
      studio_id: 18,
      // director_id: 5,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Back to the Future',
      release_date: '1985-07-03',
      country_id: 1,
      studio_id: 17,
      // director_id: 6,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: "Schindler's List",
      release_date: '1993-12-15',
      country_id: 1,
      studio_id: 17,
      // director_id: 7,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Men in Black',
      release_date: '1997-07-02',
      country_id: 1,
      studio_id: 17,
      // director_id: 8,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Rambo: First Blood',
      release_date: '1982-10-22',
      country_id: 1,
      studio_id: 16,
      // director_id: 9,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Total Recall',
      release_date: '1990-06-01',
      country_id: 1,
      studio_id: 16,
      // director_id: 10,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Terminator 2: Judgment Day',
      release_date: '1991-07-01',
      country_id: 1,
      studio_id: 16,
      // director_id: 3,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Lawrence of Arabia',
      release_date: '1962-12-10',
      country_id: 2,
      studio_id: 15,
      // director_id: 11,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Angels & Demons',
      release_date: '2009-05-13',
      country_id: 1,
      studio_id: 15,
      // director_id: 12,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Saw',
      release_date: '2004-01-19',
      country_id: 1,
      studio_id: 14,
      // director_id: 13,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Hunger Games',
      release_date: '2012-03-22',
      country_id: 1,
      studio_id: 14,
      // director_id: 14,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Lord of War',
      release_date: '2005-09-16',
      country_id: 1,
      studio_id: 14,
      // director_id: 15,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Shark Tale',
      release_date: '2004-10-01',
      country_id: 1,
      studio_id: 13,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Shrek',
      release_date: '2001-05-18',
      country_id: 1,
      studio_id: 13,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'How to Train Your Dragon',
      release_date: '2010-03-18',
      country_id: 1,
      studio_id: 13,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Madagascar',
      release_date: '2005-05-27',
      country_id: 1,
      studio_id: 13,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Saving Private Ryan',
      release_date: '1998-07-24',
      country_id: 1,
      studio_id: 12,
      // director_id: 7,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Gladiator',
      release_date: '2000-05-01',
      country_id: 1,
      studio_id: 12,
      // director_id: 23,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Taken',
      release_date: '2008-02-27',
      country_id: 4,
      studio_id: 11,
      // director_id: 24,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Transporter 2',
      release_date: '2005-08-03',
      country_id: 4,
      studio_id: 11,
      // director_id: 25,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: "Singin' in the Rain",
      release_date: '1952-03-27',
      country_id: 1,
      studio_id: 10,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Tom and Jerry',
      release_date: '1940-02-20',
      country_id: 1,
      studio_id: 10,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Spider-Man',
      release_date: '2002-04-29',
      country_id: 1,
      studio_id: 9,
      // director_id: 30,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Thor',
      release_date: '2011-04-17',
      country_id: 1,
      studio_id: 9,
      // director_id: 31,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Doctor Strange',
      release_date: '2016-10-13',
      country_id: 1,
      studio_id: 9,
      // director_id: 32,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Lord of the Rings: The Fellowship of the Ring',
      release_date: '2001-12-19',
      country_id: null,
      studio_id: 8,
      // director_id: 33,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Rush Hour',
      release_date: '1998-09-18',
      country_id: 1,
      studio_id: 8,
      // director_id: 34,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Dumb and Dumber',
      release_date: '1994-12-16',
      country_id: 1,
      studio_id: 8,
      // director_id: 35,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Roman Holiday',
      release_date: '1953-08-27',
      country_id: 1,
      studio_id: 7,
      // director_id: 37,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Godfather',
      release_date: '1972-03-14',
      country_id: 1,
      studio_id: 7,
      // director_id: 38,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Raiders of the Lost Ark',
      release_date: '1981-06-12',
      country_id: 1,
      studio_id: 7,
      // director_id: 7,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'SpongeBob SquarePants',
      release_date: '1999-05-01',
      country_id: 1,
      studio_id: 6,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Cars',
      release_date: '2006-05-26',
      country_id: 1,
      studio_id: 5,
      // director_id: 40,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Ratatouille',
      release_date: '2007-06-22',
      country_id: 1,
      studio_id: 5,
      // director_id: 41,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'WALL·E',
      release_date: '2008-06-23',
      country_id: 1,
      studio_id: 5,
      // director_id: 42,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Fast and the Furious',
      release_date: '2001-06-22',
      country_id: 1,
      studio_id: 3,
      // director_id: 43,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'King Kong (2005)',
      release_date: '2005-12-05',
      country_id: null,
      studio_id: 3,
      // director_id: 33,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Snow White and the Seven Dwarfs',
      release_date: '1937-12-21',
      country_id: 1,
      studio_id: 4,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Little Mermaid',
      release_date: '1989-11-17',
      country_id: 1,
      studio_id: 4,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Lion King',
      release_date: '1994-06-15',
      country_id: 1,
      studio_id: 4,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: '300',
      release_date: '2006-12-09',
      country_id: 1,
      studio_id: 2,
      // director_id: 49,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'I Am Legend',
      release_date: '2007-12-14',
      country_id: 1,
      studio_id: 2,
      // director_id: 50,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Matrix',
      release_date: '1999-03-24',
      country_id: 1,
      studio_id: 2,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Confucius (2010)',
      release_date: '2010-01-28',
      country_id: 3,
      studio_id: 20,
      // director_id: 53,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Crouching Tiger, Hidden Dragon: Sword of Destiny',
      release_date: '2016-02-18',
      country_id: 3,
      studio_id: 20,
      // director_id: 54,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'The Great Wall',
      release_date: '2016-12-06',
      country_id: 3,
      studio_id: 20,
      // director_id: 55,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Scandal (1950 film)',
      release_date: '1950-04-30',
      country_id: 5,
      studio_id: 21,
      // director_id: 56,
      poster: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    
    
  ]
};