module.exports = {
  studios: [
    {
      title: '20th Century Fox',
      foundation_year: '1935-05-31',
      country_id: 1,
      logo: '20th Century Logo',
      web_site: 'http://www.20thcenturystudios.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Warner Bros.',
      foundation_year: '1918-05-31',
      country_id: 1,
      logo: 'WB Logo',
      web_site: 'http://www.warnerbros.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Universal Pictures',
      foundation_year: '1912-05-31',
      country_id: 1,
      logo: 'Universal Logo',
      web_site: 'http://www.universalpictures.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Walt Disney',
      foundation_year: '1923-05-31',
      country_id: 1,
      logo: 'Disney Logo',
      web_site: 'http://www.waltdisney.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Pixar Animation Studios',
      foundation_year: '1979-05-31',
      country_id: 1,
      logo: 'Pixar Logo',
      web_site: 'http://www.pixar.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Nickelodeon Movies',
      foundation_year: '1995-05-31',
      country_id: 1,
      logo: 'Nickelodeon Logo',
      web_site: 'http://www.nick.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Paramount Pictures Corporation',
      foundation_year: '1912-05-31',
      country_id: 1,
      logo: 'Paramount Logo',
      web_site: 'http://www.paramount.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'New Line Cinema',
      foundation_year: '1967-05-31',
      country_id: 1,
      logo: 'New Line Logo',
      web_site: 'http://www.warnerbros.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Marvel Studios, LLC',
      foundation_year: '1993-05-31',
      country_id: 1,
      logo: 'Marvel Logo',
      web_site: 'http://www.facebook.com/marvelstudios/',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Metro-Goldwyn-Mayer',
      foundation_year: '1924-05-31',
      country_id: 1,
      logo: 'Met-Gol-Mayer Logo',
      web_site: 'http://www.mgm.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'EuropaCorp',
      foundation_year: '2000-05-31',
      country_id: 4,
      logo: 'EuropaCorp Logo',
      web_site: 'http://www.europacorp.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'DreamWorks Pictures',
      foundation_year: '1994-05-31',
      country_id: 1,
      logo: 'DreamWorks Logo',
      web_site: 'http://www.dreamworks.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'DreamWorks Animation',
      foundation_year: '1994-05-31',
      country_id: 1,
      logo: 'DreamWorks Logo',
      web_site: 'http://www.dreamworks.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Lionsgate',
      foundation_year: '1976-05-31',
      country_id: 8,
      logo: 'Lionsgate Logo',
      web_site: 'http://www.lionsgate.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Columbia Pictures Industries, Inc.',
      foundation_year: '1919-05-31',
      country_id: 1,
      logo: 'Columbia Logo',
      web_site: 'http://www.sonypictures.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Carolco Pictures, Inc.',
      foundation_year: '1976-05-31',
      country_id: 1,
      logo: 'Carolco Logo',
      web_site: 'http://www.facebook.com/carolcopictures/',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Amblin Entertainment',
      foundation_year: '1982-05-31',
      country_id: 1,
      logo: 'Amblin Logo',
      web_site: 'http://amblin.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Gaumont',
      foundation_year: '1895-05-31',
      country_id: 4,
      logo: 'Gaumont Logo',
      web_site: 'http://gaumonttelevision.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Heyday Films',
      foundation_year: '1997-05-31',
      country_id: 2,
      logo: 'Heyday Logo',
      web_site: 'http://www.waltdisney.com',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'China Film Group Corporation',
      foundation_year: '1999-05-31',
      country_id: 3,
      logo: 'China Film Logo',
      web_site: 'http://www.zgdygf.com/',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Shochiku',
      foundation_year: '1895-05-31',
      country_id: 5,
      logo: 'Shochiku Logo',
      web_site: 'http://www.shochiku.co.jp/global/',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Itala Film',
      foundation_year: '1905-05-31',
      country_id: 11,
      logo: 'Itala Film Logo',
      web_site: 'http://guide_to_cinema.en-academic.com/1009/Itala_film',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      title: 'Studio Green',
      foundation_year: '2006-05-31',
      country_id: 10,
      logo: 'Studio Green Logo',
      web_site: 'http://en.wikipedia.org/wiki/Studio_Green',
      created_at: new Date(),
      updated_at: new Date(),
    },
    
  ]
};